services:
  ubuntu-target:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: kisa-ubuntu
    hostname: ubuntu-target
    ports:
      - "2222:22"
    networks:
      - kisa-lab

  rocky-target:
    build:
      context: .
      dockerfile: Dockerfile.rocky
    container_name: kisa-rocky
    hostname: rocky-target
    ports:
      - "2223:22"
    networks:
      - kisa-lab

networks:
  kisa-lab:
    driver: bridge